# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'RNNativeMrzScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  
  # Pods for RNNativeMrzScanner
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge', # Include this for RN >= 0.47
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # Needed for debugging
  'RCTAnimation', # Needed for FlatList and animations running on native UI thread
  'RCTImage'
  # Add any other subspecs you want to use in your project
  ]
 
  pod "PassportScanner"

end
